# inventory file so that ansible can connect to the hosts. It allows us to specify which hosts are ec2-user and which ones use ubuntu
[amazon_linux]
# Paste Amazon Linux private IPs after terraform apply
10.0.3.107 ansible_user=ec2-user
10.0.4.28 ansible_user=ec2-user
10.0.3.203 ansible_user=ec2-user

[ubuntu]
# Paste Ubuntu private IPs after terraform apply
10.0.3.165 ansible_user=ubuntu
10.0.3.171 ansible_user=ubuntu
10.0.4.172 ansible_user=ubuntu

