# inventory file so that ansible can connect to the hosts. It allows us to specify which hosts are ec2-user and which ones use ubuntu
[amazon_linux]
# Paste Amazon Linux private IPs after terraform apply
10.0.3.194 ansible_user=ec2-user
10.0.4.56 ansible_user=ec2-user
10.0.3.79 ansible_user=ec2-user

[ubuntu]
# Paste Ubuntu private IPs after terraform apply
10.0.3.186 ansible_user=ubuntu
10.0.3.214 ansible_user=ubuntu
10.0.4.227 ansible_user=ubuntu

